### ISSUE TITLE
[Bug] Buffer is not maintained and redundant buffer is returned after tracing bert example

### ISSUE THREAD

**Issue by szhengac** [awslabs/slapo#13]
HF bert models have two buffers: `position_ids` and `token_type_ids`, so `model.state_dict` is expected to output both. However we only found `position_ids` is returned from `model.state_dict` while `token_type_ids` is missing. Also there is another redundant `mod.submod_0.submod_0.layer_0.attention.self_m.module.FusedQKV_0.fused_linear.weight` appeared in the `model.state_dict`

**Comment by chhzh123** [comment]
For the first problem, it is because HF BERT declares `token_type_ids` as non-persistent, which means it will not be a part of the buffer. See [this line](https://github.com/huggingface/transformers/blob/v4.25.1/src/transformers/models/bert/modeling_bert.py#L197-L199).

For the second one, it is related to #30, where we rename the SelfAttention module as `self_m` instead of `self` declared in the HF model. The latter may cause problem since it conflicts with the Python keyword and makes the traced module fail.
